export default function CodePreviewDark() {
  return (
    <section className="bg-primary text-on-primary py-xxl overflow-hidden relative">
      <div className="max-w-7xl mx-auto px-margin-desktop px-margin-mobile flex flex-col md:flex-row gap-xl items-center">
        
        {/* Left copy */}
        <div className="w-full md:w-1/3 z-10">
          <span className="text-[#a78bfa] font-label-sm tracking-widest uppercase mb-4 block">No Vendor Lock-in</span>
          <h2 className="font-display-lg text-[40px] leading-tight mb-6 font-light">
            Own the code. <br/> Empower your team.
          </h2>
          <p className="text-on-surface-variant text-[18px] leading-relaxed font-body-md mb-8">
            You are not renting software. Architeq writes clean, documented, standard React and Node.js code. Export it, commit it to GitHub, and let your engineering team maintain it forever.
          </p>

          <div className="flex flex-col gap-6">
            <div className="border-l-2 border-[#6366f1] pl-4">
              <h4 className="font-headline-md text-[18px] mb-1">Human-readable</h4>
              <p className="text-sm text-on-surface-variant font-body-md">Code structured exactly how a Senior Engineer would write it.</p>
            </div>
            <div className="border-l-2 border-[#a78bfa] pl-4">
              <h4 className="font-headline-md text-[18px] mb-1">Self-hosted</h4>
              <p className="text-sm text-on-surface-variant font-body-md">Deploy anywhere. You hold the keys to the kingdom.</p>
            </div>
          </div>
        </div>

        {/* Right Code Block */}
        <div className="w-full md:w-2/3 relative z-10">
          <div className="bg-[#0f0f13] rounded-2xl border border-[rgba(255,255,255,0.1)] shadow-2xl p-6 font-mono text-[14px] leading-relaxed overflow-x-auto relative">
             <div className="flex items-center gap-2 mb-6 border-b border-[rgba(255,255,255,0.1)] pb-4">
              <span className="w-3 h-3 rounded-full bg-[#ff5f57]" />
              <span className="w-3 h-3 rounded-full bg-[#febc2e]" />
              <span className="w-3 h-3 rounded-full bg-[#28c840]" />
              <span className="text-[#6b7280] text-xs ml-2">src/services/TransactionLedger.ts</span>
            </div>
            <pre>
              <span className="text-[#6b7280]">{'// Generated by Architeq DDAI Engine'}</span>{'\n'}
              <span className="text-[#c084fc]">import</span>
              <span className="text-[#e5e7eb]">{` { Injectable, Transactional } `}</span>
              <span className="text-[#c084fc]">from</span>
              <span className="text-[#86efac]">{` '@nestjs/common'`}</span>
              <span className="text-[#6b7280]">;</span>{'\n\n'}
              <span className="text-[#e5e7eb]">@</span>
              <span className="text-[#93c5fd]">Injectable</span>
              <span className="text-[#e5e7eb]">{'()'}</span>{'\n'}
              <span className="text-[#c084fc]">export class</span>
              <span className="text-[#a78bfa]">{' LedgerService '}</span>
              <span className="text-[#e5e7eb]">{'{'}</span>{'\n'}
              <span className="text-[#e5e7eb]">{'  @'}</span>
              <span className="text-[#93c5fd]">Transactional</span>
              <span className="text-[#e5e7eb]">{'()'}</span>{'\n'}
              <span className="text-[#c084fc]">{'  async '}</span>
              <span className="text-[#93c5fd]">recordTransfer</span>
              <span className="text-[#e5e7eb]">{'('}</span>
              <span className="text-[#fbbf24]">amount</span>
              <span className="text-[#e5e7eb]">{': '}</span>
              <span className="text-[#a78bfa]">number</span>
              <span className="text-[#e5e7eb]">{', '}</span>
              <span className="text-[#fbbf24]">fromId</span>
              <span className="text-[#e5e7eb]">{': '}</span>
              <span className="text-[#a78bfa]">string</span>
              <span className="text-[#e5e7eb]">{') {'}</span>{'\n'}
              <span className="text-[#c084fc]">{'    await '}</span>
              <span className="text-[#c084fc]">this</span>
              <span className="text-[#e5e7eb]">.</span>
              <span className="text-[#fbbf24]">accounts</span>
              <span className="text-[#e5e7eb]">.</span>
              <span className="text-[#93c5fd]">debit</span>
              <span className="text-[#e5e7eb]">{'(fromId, amount);'}</span>{'\n'}
              <span className="text-[#c084fc]">{'    return '}</span>
              <span className="text-[#c084fc]">this</span>
              <span className="text-[#e5e7eb]">.</span>
              <span className="text-[#fbbf24]">ledger</span>
              <span className="text-[#e5e7eb]">.</span>
              <span className="text-[#93c5fd]">commit</span>
              <span className="text-[#e5e7eb]">{'();'}</span>{'\n'}
              <span className="text-[#e5e7eb]">{'  }'}</span>{'\n'}
              <span className="text-[#e5e7eb]">{'}'}</span>
            </pre>

            {/* Glowing background accent */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[80%] h-[80%] bg-[#6366f1] opacity-20 blur-[100px] pointer-events-none -z-10" />
          </div>
        </div>

      </div>
    </section>
  );
}
