import Reveal from '@/components/Reveal';

export default function CodePreview() {
  return (
    <section className="py-[60px]" aria-labelledby="code-title">
      <div className="max-w-[1120px] mx-auto px-6 relative z-10">

        <Reveal>
          <p className="flex items-center gap-3 font-mono text-[11px] font-semibold tracking-[0.2em] uppercase text-[var(--accent-purple-bright)] mb-4 after:flex-1 after:h-px after:bg-[var(--border-subtle)] after:content-['']">
            // What gets generated
          </p>
        </Reveal>

        <Reveal delay={80}>
          <h2
            id="code-title"
            className="font-extrabold tracking-tight text-[var(--text-primary)] mb-12"
            style={{ fontSize: 'clamp(28px, 4vw, 42px)' }}
          >
            From <span className="gradient-text-accent">Schema to System</span>
          </h2>
        </Reveal>

        <Reveal delay={160}>
          <div
            className="rounded-[var(--radius-lg)] overflow-hidden border border-[var(--border-subtle)]"
            style={{ background: '#080810', boxShadow: '0 24px 60px rgba(0,0,0,0.5)' }}
            role="img"
            aria-label="Generated backend code example"
          >
            {/* Title bar */}
            <div
              className="flex items-center gap-2 px-[18px] py-[14px] border-b border-[var(--border-subtle)]"
              style={{ background: 'rgba(10,10,20,0.8)' }}
            >
              <span className="w-3 h-3 rounded-full bg-[#ff5f57]" aria-hidden="true" />
              <span className="w-3 h-3 rounded-full bg-[#febc2e]" aria-hidden="true" />
              <span className="w-3 h-3 rounded-full bg-[#28c840]" aria-hidden="true" />
              <span className="font-mono text-xs text-[var(--text-muted)] ml-2">
                architeq.generated.ts
              </span>
            </div>

            {/* Code body */}
            <div className="px-6 py-7 overflow-x-auto">
              <pre className="font-mono text-[13px] leading-[1.8] m-0">
                <span className="text-[#475569]">{`// ✦ Generated by Architeq DDAI Engine — v1.0`}</span>{'\n'}
                <span className="text-[#475569]">{`// ✦ Schema: ecommerce_platform.ateq | Build time: 0.8s`}</span>{'\n\n'}
                <span className="text-[#c084fc]">import</span>
                <span className="text-[#cbd5e1]">{` { Injectable, RateLimit, Audit } `}</span>
                <span className="text-[#c084fc]">from</span>
                <span className="text-[#86efac]">{` '@architeq/core'`}</span>
                <span className="text-[#94a3b8]">;</span>{'\n'}
                <span className="text-[#c084fc]">import</span>
                <span className="text-[#cbd5e1]">{` { OrderRepository, UserRepository } `}</span>
                <span className="text-[#c084fc]">from</span>
                <span className="text-[#86efac]">{` './repositories'`}</span>
                <span className="text-[#94a3b8]">;</span>{'\n\n'}
                <span className="text-[#cbd5e1]">@</span>
                <span className="text-[#93c5fd]">Injectable</span>
                <span className="text-[#cbd5e1]">{'() @'}</span>
                <span className="text-[#93c5fd]">RateLimit</span>
                <span className="text-[#cbd5e1]">{'({ rpm: '}</span>
                <span className="text-[#f9a8d4]">1000</span>
                <span className="text-[#cbd5e1]">{' })'}</span>{'\n'}
                <span className="text-[#c084fc]">export class</span>
                <span className="text-[#a78bfa]">{' OrderService '}</span>
                <span className="text-[#cbd5e1]">{'{'}</span>{'\n'}
                <span className="text-[#c084fc]">{'  constructor'}</span>
                <span className="text-[#cbd5e1]">{'('}</span>{'\n'}
                <span className="text-[#c084fc]">{'    private readonly '}</span>
                <span className="text-[#fbbf24]">orders</span>
                <span className="text-[#cbd5e1]">{': '}</span>
                <span className="text-[#a78bfa]">OrderRepository</span>
                <span className="text-[#94a3b8]">,</span>{'\n'}
                <span className="text-[#c084fc]">{'    private readonly '}</span>
                <span className="text-[#fbbf24]">users</span>
                <span className="text-[#cbd5e1]">{': '}</span>
                <span className="text-[#a78bfa]">UserRepository</span>
                <span className="text-[#94a3b8]">,</span>{'\n'}
                <span className="text-[#cbd5e1]">{'  ) {}'}</span>{'\n\n'}
                <span className="text-[#cbd5e1]">{'  @'}</span>
                <span className="text-[#93c5fd]">Audit</span>
                <span className="text-[#cbd5e1]">{'({ level: '}</span>
                <span className="text-[#86efac]">{`'critical'`}</span>
                <span className="text-[#cbd5e1]">{' })'}</span>{'\n'}
                <span className="text-[#c084fc]">{'  async '}</span>
                <span className="text-[#93c5fd]">createOrder</span>
                <span className="text-[#cbd5e1]">{'('}</span>
                <span className="text-[#fbbf24]">dto</span>
                <span className="text-[#cbd5e1]">{': '}</span>
                <span className="text-[#a78bfa]">CreateOrderDto</span>
                <span className="text-[#cbd5e1]">{', '}</span>
                <span className="text-[#fbbf24]">actor</span>
                <span className="text-[#cbd5e1]">{': '}</span>
                <span className="text-[#a78bfa]">AuthenticatedUser</span>
                <span className="text-[#cbd5e1]">{'): '}</span>
                <span className="text-[#a78bfa]">Promise</span>
                <span className="text-[#94a3b8]">{'<'}</span>
                <span className="text-[#a78bfa]">Order</span>
                <span className="text-[#94a3b8]">{'>'}</span>
                <span className="text-[#cbd5e1]">{' {'}</span>{'\n'}
                <span className="text-[#c084fc]">{'    await '}</span>
                <span className="text-[#c084fc]">this</span>
                <span className="text-[#94a3b8]">.</span>
                <span className="text-[#fbbf24]">users</span>
                <span className="text-[#94a3b8]">.</span>
                <span className="text-[#93c5fd]">assertRole</span>
                <span className="text-[#cbd5e1]">{'(actor, '}</span>
                <span className="text-[#86efac]">{`'customer'`}</span>
                <span className="text-[#cbd5e1]">{');'}</span>{'\n'}
                <span className="text-[#c084fc]">{'    const '}</span>
                <span className="text-[#fbbf24]">validated</span>
                <span className="text-[#94a3b8]">{' = '}</span>
                <span className="text-[#c084fc]">await </span>
                <span className="text-[#93c5fd]">validateSchema</span>
                <span className="text-[#cbd5e1]">{'(dto, '}</span>
                <span className="text-[#a78bfa]">OrderSchema</span>
                <span className="text-[#cbd5e1]">{');'}</span>{'\n'}
                <span className="text-[#c084fc]">{'    return '}</span>
                <span className="text-[#c084fc]">this</span>
                <span className="text-[#94a3b8]">.</span>
                <span className="text-[#fbbf24]">orders</span>
                <span className="text-[#94a3b8]">.</span>
                <span className="text-[#93c5fd]">create</span>
                <span className="text-[#cbd5e1]">{'(validated, actor);'}</span>{'\n'}
                <span className="text-[#cbd5e1]">{'  }'}</span>{'\n'}
                <span className="text-[#cbd5e1]">{'}'}</span>{'\n\n'}
                <span className="text-[#475569]">{`// ✦ + 47 more files generated (controllers, repos, migrations, tests, OpenAPI spec)`}</span>
              </pre>
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  );
}
